config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'health/index'

  # Defines the root path route ("/")
  root "brands#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :brands do
        resources :products
      end
    end
  end

  resources :brands
  # resources :brands do
  #   resources :products
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  # model associations
  has_many :products, dependent: :destroy

  # validations
  validates_presence_of :name

  def self.ransackable_attributes(auth_object = nil)
    column_names + _ransackers.keys
  end

  def self.ransackable_associations(auth_object = nil)
    reflect_on_all_associations.map { |a| a.name.to_s } + _ransackers.keys
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # model association
  belongs_to :brand

  # validation
  validates_presence_of :name, :type
end

app/models/website.rb
class Website < ApplicationRecord
  # Eventually this will be something like a store website, where brands can be purchased from.
  belongs_to :brand

  validates_presence_of :name, :url
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  include Response
  include ExceptionHandler
end

app/controllers/api/v1/brands_controller.rb
class Api::V1::BrandsController < Api::V1::BaseController
  before_action :set_brand, only: [:show, :update, :destroy]

  # GET /brands
  def index
    @brands = Brand.all
    json_response(@brands)
  end

  # POST /brands
  def create
    @brand = Brand.create!(brand_params)
    json_response(@brand, :created)
  end

  # GET /brands/:id
  def show
    json_response(@brand)
  end

  # PUT /brands/:id
  def update
    @brand.update(brand_params)
    head :no_content
  end

  # DELETE /brands/:id
  def destroy
    @brand.destroy
    head :no_content
  end

  private

  def brand_params
    # whitelist params
    params.permit(:name, :url)
  end

  def set_brand
    @brand = Brand.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  include Pagy::Backend

  def index
    @q = Brand.ransack(params[:q])
    @pagy, @brands = pagy(@q.result(distinct: true), items: 10)
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to @brand
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])

    if @brand.update(brand_params)
      redirect_to @brand
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :url, :cruelty_free, :peta, :leaping_bunny)
  end
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  # provides the more graceful `included` method
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/health_controller.rb
class HealthController < ApplicationController
  def index
    render json: { status: 'online' }, status: 200
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/brands/_brands.html.erb
<%= turbo_frame_tag "brands", class: "shadow overflow-hidden rounded border-b border-gray-200" do %>
  <div style="margin: 20px;">
    <table
      class="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-page-list="[10, 25, 50, 100]"
      data-show-footer="true"
    >
      <thead class="bg-gray-800 text-white">
        <tr>
          <th id="brand-name" data-sortable="true" data-field="name" class="text-left py-3 px-6 uppercase font-semibold text-sm hover:cursor-pointer">
            <span>Name</span>
          </th>
          <th id="brand-official-site" data-field="brand-official-site" class="text-left py-3 px-6 uppercase font-semibold text-sm hover:cursor-pointer">
            <%= link_to("Official WebSite", brands_path(column: "url")) %>
          </th>
          <th id="brand-certs" data-field="brand-certs" class="text-left py-3 px-6 uppercase font-semibold text-sm hover:cursor-pointer">
            <span>Certifications</span>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @brands.each do |brand| %>
          <tr>
            <td class="text-left py-3 px-6"><%= brand.name %></td>
            <td class="text-left py-3 px-6"><%= brand.url ? (link_to "Official Site", brand.url) : "" %></td>
            <td class="text-left py-3 px-6"><%= brand.cruelty_free %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/brands/_form.html.erb
<%= form_with model: brand do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% brand.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :cruelty_free %><br>
    <%= form.check_box :cruelty_free %>
  </div>

  <div>
    <%= form.label :peta %><br>
    <%= form.check_box :peta %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Edit Brand</h1>

<%= render "form", brand: @brand %>

app/views/brands/index.html.erb
<div class="flex flex-col">
  <h1 class="m-1 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl">
  Brands
  </h1>


  <div class="my-5 mx-20 overflow-x-auto">
    <div class="p-1.5 min-w-full inline-block align-middle">
      <div class="rounded-lg shadow overflow-hidden dark:border-gray-700 dark:shadow-gray-900">

        <%= search_form_for @q do |f| %>
          <div class="float-right m-2.5">
            <div class="relative">
              <%= f.search_field :name_cont, 
                class: "pull-left pt-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 focus:ring-blue-500 focus:border-blue-500",
                placeholder: "Search by Brand Name"
              %>
              <div class="absolute inset-y-0 start-0 flex items-center pointer-events-none z-20 ps-4">
                <span class="text-gray-500"><i class="fa-solid fa-magnifying-glass"></i></span>
              </div>
            </div>
          </div>
        <% end %>

        <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
          <thead>
            <tr>
              <th scope="col" class="border rounded-l-lg px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">
                <%= sort_link(@q, :name, "Brand Name", default_order: :asc) %>
              </th>
              <th scope="col" class="border rounded-r-lg px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Official Site</th>
              <th scope="col" class="border rounded-r-lg px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Certs</th>
              <th scope="col" class="border rounded-r-lg px-6 py-3 text-start text-xs font-medium text-gray-500 uppercase">Actions</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
            <% @brands.each do |brand| %>
              <tr>
                <td class="border px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800"> <%= brand.name %></td>
                <td class="border px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800"><%= brand.url ? link_to("Official Site", brand.url) : "" %>
                <td class="border px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800"> <%= brand.peta %></td>
                <td class="border px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800"> Actions </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="flex items-center justify-center">
          <%== pagy_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render "form", brand: @brand %>

app/views/brands/show.html.erb
<h1><%= @brand.name %></h1>

<p>Cruelty-Free: <%= @brand.cruelty_free %></p>

<ul>
  <li><%= link_to "Edit", edit_brand_path(@brand) %></li>
  <li><%= link_to "Destroy", brand_path(@brand), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrueltyFreeMakeupApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>